### ISSUE TITLE
Removing old viz modules

### ISSUE THREAD

**Issue by wingedRuslan** [WhitakerLab/scona#148]
Documenting files that can be deleted after my PRs approved.

- [ ] **scona/nilearn_plotting.py**

    - [ ] `graph_to_nilearn_array`
    - [ ]  `plot_connectome_with_nilearn`
    - [ ]  `view_connectome_with_nilearn`
    - [ ]  `view_markers_with_nilearn`

All these functions are implemented in [PR #145](https://github.com/WhitakerLab/scona/pull/145).

- [ ] **scona/make_figures.py**

    - [ ] `plot_anatomical_network`
    - [ ] `anatomical_layout`

All these functions are Included in PR #140 

   - [ ] `get_anatomical_layouts` ! - **Not**
" This code takes in a BrainNetwork that has x, y, z coordinates and integer node labels (0 to n-1) for n nodes and returns three dictionaries containing appropriate pairs of coordinates for sagittal, coronal and axial slices."
   - [ ] `view_corr_mat` - **Not**

- [ ] **scona/scripts/visualisation_commands.py**
    - [ ]  `rescale` - **Not**
    - [ ] `view_corr_mat` - **Not**

Have not worked on any of these functions. `view_corr_mat` seems to work fine, so I can easily (hopefully) refactor and include in another file that has all the visualizations. Or this function could be redesigned and use `seaborn.heatmap`.

- [ ] **scona/scripts/make_figures.py** - the one with 4000 lines

    - [ ] `plot_rich_club` 
    - [ ] `plot_degree_dist`
    - [ ] `plot_network_measures`

Above 3 functions are included in PR #121 

   - [ ] `add_colorbar` - included in PR #140 
   - [ ] `setup_color_list` - included in PR #140
   - [ ] `plot_anatomical_network` -  included in PR #140

   - [ ] `plot_sagittal_network` - seems like a special case of `plot_anatomical_network` ? 
   - [ ] `pretty_scatter` - **Not**
"This function creates a scatter plot with a regression line for the y variable against the degrees of graph G"
   - [ ] `degree_r_values` - **Not**
   - [ ] `create_violin_labels` - **Not**
"A little function to create a labels list for the MT depth violin plots"
   - [ ] `violin_mt_depths` - **Not**
   - [ ] `violin_add_laminae` - **Not**
   - [ ] `old_figure_1` - **Not**
   - [ ] `old_figure_2` - **Not**
   - [ ] `old_figure_3` - **Not**
   - [ ] `partial_volume_fig` - **Not**
   - [ ] `all_mean_mt` - **Not**
   - [ ] `nodal_ct_mt` - **Not**
   - [ ] `get_von_economo_color_dict` - **Not**
   - [ ] `get_von_economo_shapes_dict` - **Not**
   - [ ] `von_economo_boxes` - **Not**
   - [ ] `von_economo_scatter` - **Not**
   - [ ] `add_four_hor_brains` - **Not**
   - [ ] `add_cells_picture` - **Not**
   - [ ] `figure_1` - **Not**
   - [ ] `figure_2` - **Not**
   - [ ] `figure_3` - **Not**
   - [ ] `figure_4` - **Not**

   - [ ] `calc_min_max` - **Not**
" Find min and max values such that all the data lies within 90% of the axis range"

   - [ ] `get_min_max_values` - **Not**
   - [ ] `plot_circular_network` - **Not**
   - [ ] `set_conn_types` - **Not**
   - [ ] `rich_edges_nodes` - **Not**
   - [ ] `results_matrix` - **Not**
   - [ ] `figs_for_talk` - **Not**
   - [ ] `network_summary_fig` - **Not**
   - [ ] `mt_degree_network_fig` - **Not**
   - [ ] `rescale` - **Not**
   - [ ] `candidate_histogram` - **Not**
   - [ ] `xyz_vs_measures` - **Not**
   - [ ] `make_combo_matrix` - **Not**
   - [ ] `make_combo_scatter` - **Not** 
   - [ ] `make_combo_figures` - **Not**
   - [ ] `parcellation_4horbrains` - **Not**
   - [ ] `mediation_figure` - **Not**

As far as I understood the code inside this file you developed is especially for your paper. @KirstieJane if you wish to have smth in scona, let me know, and I will do that!

@KirstieJane what would you like to do with:
1) view_corr_mat
2) get_anatomical_layouts
3) rescale
